### ISSUE TITLE
Resetting to maskrom assumption

### ISSUE THREAD

**Issue by d3adme4t** [edk2-porting/edk2-rk3588#1]
Hi,

Most likely the right register to send the maskrom magic sequence (0xEF08A53C) is the 0xFD58A200, instead of 0xfd588080.
(https://github.com/edk2-porting/edk2-rk35xx/blob/master/edk2-platforms/Platform/Radxa/ROCK5B/Library/ResetSystemLib/ResetSystemLib.c#L103)

Can't verify it anytime soon, but I'll update this post after checking.

**Comment by strongtz** [comment]
Well I tested it just now. Unfortunately it's still not working.
