### ISSUE TITLE
UART speed menu (feature request)

### ISSUE THREAD

**Issue by idigdoug** [edk2-porting/edk2-rk3588#102]
Could we get a menu to select the speed of UART0? That would be helpful for Windows kernel debugging since Windows cannot (yet) adjust the clock for the UART itself and a lot of serial adapters can't manage 1.5Mbps.

Suggest that we have a menu option to select initial UART speeds of 1.5Mbps, 500000, and 115200.

**Comment by mariobalanica** [comment]
bc0a1bc83360c8a8a5e17a97167ae740525f1134
