### ISSUE TITLE
string.h no such file or directory

### ISSUE THREAD

**Issue by moritz-meier** [edk2-porting/edk2-rk3588#117]
When building the master branch with

` ./build.sh --device orangepi-5plus --release Debug`

in the [edk2 fedora:39](https://github.com/tianocore/containers/pkgs/container/containers%2Ffedora-39-build) container environment, the build fails with the error: 

`edk2-rk3588/edk2-rockchip/Silicon/Rockchip/Library/DisplayLib/DwHdmiQpLib.c:24:10: fatal error: string.h: No such file or directory`

**Comment by mariobalanica** [comment]
Pushed a fix, please let me know if it builds now.

**Comment by moritz-meier** [comment]
Works!  thanks.
