### ISSUE TITLE
orangepi 5 plus:  0.9.1 can not load win11 install iso, 0.9 is ok

### ISSUE THREAD

**Issue by alecthw** [edk2-porting/edk2-rk3588#119]

**Comment by mariobalanica** [comment]
What are you booting the ISO from?

I cannot reproduce this and there wasn't any change in v0.9.1 that could've broken Windows support.

**Comment by alecthw** [comment]
ISO and installation built by Raspberry imager tool both not ok. The circle loading run a few seconds， then it stop loading.
Waiting a long time， no reaction……

**Comment by mariobalanica** [comment]
Btw, Windows is expected to freeze if you have an NVME drive connected. A workaround is available in the Discord server.

v0.9.1 fixed a PCIe enumeration bug, so the reason why v0.9 works is likely because it didn't even detect your NVME drive to begin with.

**Comment by alecthw** [comment]
> Btw, Windows is expected to freeze if you have an NVME drive connected. A workaround is available in the Discord server.
> 
> v0.9.1 fixed a PCIe enumeration bug, so the reason why v0.9 works is likely because it didn't even detect your NVME drive to begin with.

Thank you very much. I'll try it later.
