### ISSUE TITLE
add kernel 6.1.43 dtb support to orangepi5plus

### ISSUE THREAD

**Issue by PrestarLin** [edk2-porting/edk2-rk3588#122]
orangepi5plus has update the kernel of Linux to 6.1.43,but the uefi doesnot support it,i try to override the dtb,and overlays in the  /boot/efi/dtb directoy, but it still stay in the *init....kernel..*(the grub guild second line)...please help me,thanks!

**Comment by mariobalanica** [comment]
https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#device-tree-configuration
