### ISSUE TITLE
Can I use Ventoy to boot OS UEFI with this source ?

### ISSUE THREAD

**Issue by huyhuynh2210** [edk2-porting/edk2-rk3588#135]
I have Orange Pi 5 Plus, USB Ventoy having file iso arm64 from UUpdump.net and SD card wrote this source img. I tried to boot but it is not work! Ventoy have support ARM64 UEFI too.

**Comment by musover** [comment]
I have done so successfully from a USB flash drive on the regular Orange Pi 5

**Comment by huyhuynh2210** [comment]
> I have done so successfully from a USB flash drive on the regular Orange Pi 5

Sound great! Am I wrong at any step ?

**Comment by mariobalanica** [comment]
Ventoy works just fine. Please provide more details of what you're trying to boot with it, serial logs, etc..
