### ISSUE TITLE
Emmc Storage never detected.

### ISSUE THREAD

**Issue by DarkevilPT** [edk2-porting/edk2-rk3588#145]
Hi I dont know what I am doing wrong here or if this is procedure but... I flashed the emmc with uefi and flashed the usb with opensuse it all boots up but when it comes to the system operative installation it doesnt detects my board emmc storage.

I also erased my board emmc storage flashed an MicroSD with uefi booted up into openSuse installation and.. the same issue happens.. it only detects the usb from where its booting it from and not the emmc storage.

What am I doing wrong here ? Radxa CM5 / Khadas Edge 2. ( Both have the same issue ).

**Comment by mariobalanica** [comment]
Check out: https://github.com/edk2-porting/edk2-rk3588?tab=readme-ov-file#supported-oses

That's expected in ACPI mode. You should be using a device tree compatible with your Linux kernel instead.
