### ISSUE TITLE
release 0.11.2 not start from SD-card

### ISSUE THREAD

**Issue by wmport** [edk2-porting/edk2-rk3588#147]
release 0.11.2 , nanopc-t6 does not boot with image installed on SD card, starts os on mmc

**Comment by wmport** [comment]
Clear spi flash, and all works.

**Comment by hrw** [comment]
if it works after cleaning flash then can you close this issue?

**Comment by wmport** [comment]
> если после очистки флэш-памяти все заработает, то можно ли закрыть эту проблему?
yes
