### ISSUE TITLE
[Question] Support to run Multiple OS off grub bootloader?

### ISSUE THREAD

**Issue by psmdv** [edk2-porting/edk2-rk3588#150]
I would like to know. whether Is it possible to run Grub bootloader with multiple OS side by side with EDK2 Firmware on a Orangepi 5 Plus or RK3588 device?

Like Combinations
ArchLinux Mainline - USB/eMMC 
Ubuntu Mainline - NVMe

(or)

Windows 11 - USB or eMMC
Ubuntu Mainline - NVMe

I hope someone can answer this question whether this is supported. This question may be reference to someone else looking for the same info. or README can be updated to include this information

**Comment by Rippanda12** [comment]
should be the same as dual(multi) booting on x86 you just have to find UEFI images with the right kernel

**Comment by psmdv** [comment]
Thanks for the reply. Sorry for the delayed response. :)
