### ISSUE TITLE
WoR Images

### ISSUE THREAD

**Issue by macooper59** [edk2-porting/edk2-rk3588#165]
Hello Everyone,

Which one of the images is for the Orange Pi5 Plus? [https://github.com/edk2-porting/edk2-rk3588/releases](WoR Images)

**Comment by Rippanda12** [comment]
https://objects.githubusercontent.com/github-production-release-asset-2e65be/567314232/d2ab0fe1-4ed1-43e2-b0f5-1acde0362b84?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241007%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241007T074149Z&X-Amz-Expires=300&X-Amz-Signature=bbe82a2505a98607ea6a6d90bf95eea7a9eebe704c2f1e974a7162426086c832&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D&response-content-type=application%2Foctet-stream

orangepi-5plus_UEFI_Release_v0.11.2.img

**Comment by macooper59** [comment]
> https://objects.githubusercontent.com/github-production-release-asset-2e65be/567314232/d2ab0fe1-4ed1-43e2-b0f5-1acde0362b84?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241007%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241007T074149Z&X-Amz-Expires=300&X-Amz-Signature=bbe82a2505a98607ea6a6d90bf95eea7a9eebe704c2f1e974a7162426086c832&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D&response-content-type=application%2Foctet-stream
> 
> orangepi-5plus_UEFI_Release_v0.11.2.img

Thank you sir

**Comment by macooper59** [comment]
It says the link doesn't work?

[image: image.png]

Thanks,

Michael Cooper
*Certified Linux Professional*
*Docker/Kubernetes Trained*
RPi Hobby Blog <http://www.rpihobby.us>

**Comment by mariobalanica** [comment]
GitHub may truncate the list of assets. There's a link at the bottom to show all of them.
