### ISSUE TITLE
16 MB image possible ?

### ISSUE THREAD

**Issue by ScarFez** [edk2-porting/edk2-rk3588#28]
Can you post a 16 MB image (16,777,216 bytes) of the [rock-5b_UEFI_Release_v0.7.1.img](https://github.com/edk2-porting/edk2-rk3588/releases/download/v0.7.1/rock-5b_UEFI_Release_v0.7.1.img) ?

I was unable to use that image, maybe it's because I tried to dd it to spi, but I have no other method

**Comment by mariobalanica** [comment]
The image has its current size on purpose, in order to not overwrite user settings area. You can zero the SPI NOR with dd beforehand if you wish/need to.

**Comment by ScarFez** [comment]
Ok, thanks. I just realized I don't have the efi files for it anyhow...
