### ISSUE TITLE
ETHERNET Is Not Working

### ISSUE THREAD

**Issue by Bryce10111** [edk2-porting/edk2-rk3588#29]

**Comment by Marcinoo97** [comment]
what board? what NIC does it have? do you mean its not working in UEFI itself or OS you started via UEFI?

**Comment by Bryce10111** [comment]
[Orange Pi 5]

**Comment by mariobalanica** [comment]
Do you expect it to work in UEFI or a specific OS? Please give more details.
None of these scenarios are yet supported, but ACPI support is coming soon-ish.

**Comment by Bryce10111** [comment]
In OS
