### ISSUE TITLE
How Can I recompile The Drivers So I Can Make A New Boot Logo

### ISSUE THREAD

**Issue by Bryce10111** [edk2-porting/edk2-rk3588#32]

**Comment by duetg** [comment]
The logo is in the folder of source code. Like this:

https://github.com/edk2-porting/edk2-rk3588/blob/master/edk2-rockchip/Platform/OrangePi/Drivers/LogoDxe/Logo.bmp

You may change logo image of the platform which you have.

The building instructions are at the bottom of readme page.

**Comment by mariobalanica** [comment]
First step would be to make yourself familiar with the Readme.
It's also possible to fork this repository, make the changes and let GitHub build it for you.

**Comment by Bryce10111** [comment]
But How

**Comment by duetg** [comment]
Follow the Building section of README.md
After step 2, change the logo image of the platform which you have.
The do the last step.

**Comment by Bryce10111** [comment]
How Can I Do That
