### ISSUE TITLE
Project Mu support

### ISSUE THREAD

**Issue by mariobalanica** [edk2-porting/edk2-rk3588#68]
We don't have to give up on edk2, they can be both supported in the same codebase with minimal changes.

**Comment by mariobalanica** [comment]
I was mainly interested in the new frontpage UI, but turns out it's unusable. HII support is really lacking and the (few) menus present are hard to navigate with a keyboard.

Project MU does have some nice security-related bits, but overall it doesn't seem worth the hassle. 
Sticking to plain EDK2 is better in case anyone feels like upstreaming the platform.

As such, I'm closing this.

**Comment by BigfootACA** [comment]
yes, for project mu you are probably looking for https://github.com/woa-msmnile/msmnilePkg

**Comment by sunflower2333** [comment]
if you want to have a try, i have a broken mu repo for my rock5b.
https://github.com/sunflower2333/mu-rk5b

**Comment by sunflower2333** [comment]
![937D6BAAF0A72F2CFF956B190C1CFF8D](https://github.com/edk2-porting/edk2-rk3588/assets/54024877/6b75c3f1-b92b-44c6-b78d-5de43e775d06)
