### ISSUE TITLE
256MB RAM wasted as framebuffer. 

### ISSUE THREAD

**Issue by Marcinoo97** [edk2-porting/edk2-rk3588#71]
96MB should be max possible value for 2 4k screens.

**Comment by mariobalanica** [comment]
Related to #45

**Comment by mariobalanica** [comment]
Fixed in 73bdaca7133c3c3a964d6c387122f271990751bc, it was hardcoded to 128 MB.

256 MB is reserved by MMIO + a few more MBs by firmware regions and faulty memory ranges.
