### ISSUE TITLE
/simple-init/libs/freetype File missing

### ISSUE THREAD

**Issue by maolihu751** [edk2-porting/edk2-rk3588#83]
A file is missing when the remote repository is cloned to the local.

**Comment by mariobalanica** [comment]
`git submodule update --init --recursive`

**Comment by maolihu751** [comment]
I tried git submodule update-init-recursive but still failed to solve this problem. Open /simple-init/libs/freetype to display 404.

**Comment by mariobalanica** [comment]
Yeah, it seems the freetype submodule link is down. I have removed the dependency as it isn't necessary.

**Comment by maolihu751** [comment]
After deleting the freetype related submodule, it can clone normally, but it can not compile
![image](https://github.com/edk2-porting/edk2-rk3588/assets/143320717/da43f74b-c053-4921-a81f-34ccbbcad49e)
