### ISSUE TITLE
SPI2 PMIC Iomux configuration on CLK sel

### ISSUE THREAD

**Issue by UtsavBalar1231** [edk2-porting/edk2-rk3588#86]
In the `Rk806SpiIomux` function inside the **RockchipPlatformLib** there seems to be some problem with `CRU_CLKSEL_CON59` register 

```
MmioWrite32(NS_CRU_BASE + CRU_CLKSEL_CON59, (0x00C0UL << 16) | 0x0080);
```

According to the RK3588 TRM 

```text
CRU_CLKSEL_CON59
Address: Operational Base + offset (0x03EC)

Bit 31:16: configures the write enable for lower 16bits

`0x00C0` means `0000 0000 1100 0000`

So, bits 4-7 are selected for write_enable

Bit 7:6:
clk_spi2_sel
clk_spi2 clock mux.
2'b00: clk_matrix_200m_src
2'b01: clk_matrix_150m_src
2'b10: xin_osc0_func


Bit 5:4: 
clk_spi1_sel
clk_spi1 clock mux.
2'b00: clk_matrix_200m_src
2'b01: clk_matrix_150m_src
2'b10: xin_osc0_func

So, according to `0080`, we are enabling xin_osc0_func (`0000 0000 1000 0000` )

```

Inside the rk3588 linux kernel `rk3588-rk806-single.dtsi`, we are selecting `CLK_SPI2` which is a 200Mhz clock

And again according to TRM, that should be `clk_spi_sel`   `2'b00 clk_matric_200m_src`.

Which would require us to change it to **write_enable 0x00C0 to 0x0000**.

Please check once and let me know if I am wrong.

**Comment by mariobalanica** [comment]
The SPI driver also expects a 24 MHz source clock here:
https://github.com/edk2-porting/edk2-rk3588/blob/5833bde557dbbc812c2378dae9df6a0499692dbd/edk2-rockchip/Silicon/Rockchip/Library/SpiLib/RK806.c#L589-L590
to calculate the divider.

There isn't any need to select the 200 MHz source, given that SCLK is set to just 2 MHz.
