### ISSUE TITLE
0.8 release problem with Orange Pi 5 plus and Rock 5b

### ISSUE THREAD

**Issue by harryzz** [edk2-porting/edk2-rk3588#87]
Hello,

there are problem with latest release 0.8 with rock 5b and opi 5 plus.
![PXL_20230917_101401734](https://github.com/edk2-porting/edk2-rk3588/assets/4759272/bcca4a91-9f2f-40d3-8444-cfd5bfdb162b)

**Comment by mariobalanica** [comment]
Are you trying to boot some OS? How did you flash the image?

**Comment by harryzz** [comment]
> Are you trying to boot some OS? How did you flash the image?

Yes. I have running centos 9 on both (installed on NVME). Also i have some usb sticks and sd cards with fedora, armbian etc .... With build from commit before 13-09-2023 all working fine. Probably problem is somewhere here: 
Updated EDK2 base to edk2-stable202308 OR Updated rkbin.
I have burned image to spi flash with RKDevTool v3.15. 


regards,
Zahari

**Comment by mariobalanica** [comment]
To clarify, the Synchronous Exception only appears after you attempt to boot the OS, right? Are you able to enter firmware setup or the UEFI shell on v0.8?

Can you try this build right before the EDK2 update? https://github.com/edk2-porting/edk2-rk3588/commit/7a0363351f6c6418e20163bdf2e214bc09c64809

Also, are you using a debug or release variant? I'd try both to see if there's any difference.

**Comment by harryzz** [comment]
> To clarify, the Synchronous Exception only appears after you attempt to boot the OS, right? Are you able to enter firmware setup or the UEFI shell on v0.8?
yes UEFI shell is availabe.

![rock5b_bootmanager_0 8](https://github.com/edk2-porting/edk2-rk3588/assets/4759272/b57a3c41-f810-413d-8924-cc87b46e200b)
![rock5b_uefi_shell_0 8](https://github.com/edk2-porting/edk2-rk3588/assets/4759272/d23dafbe-1599-410e-a179-c8da7d413e31)

> 
> Can you try this build right before the EDK2 update? [7a03633](https://github.com/edk2-porting/edk2-rk3588/commit/7a0363351f6c6418e20163bdf2e214bc09c64809)
commit 7a0363351f6c6418e20163bdf2e214bc09c64809 (HEAD)
Author: Mario Bălănică <mariobalanica02@gmail.com>
Date:   Fri Sep 15 01:06:44 2023 +0300

    Silicon/Rockchip: I2cDxe: Connect all controller handles at end of Dxe

    Only the first handle was connected.

<img width="892" alt="rock5b_commit 7a036335" src="https://github.com/edk2-porting/edk2-rk3588/assets/4759272/5a514dfd-13e0-4a7f-9a83-b9fb417001ae">


> 
> Also, are you using a debug or release variant? I'd try both to see if there's any difference.

I use release version from github artifacts.

**Comment by mariobalanica** [comment]
Do you have a link for the CentOS image you're using? Is it CentOS Stream 9 aarch64 from: https://www.centos.org/download/ ?

**Comment by harryzz** [comment]
> Do you have a link for the CentOS image you're using? Is it CentOS Stream 9 aarch64 from: https://www.centos.org/download/ ?

yes. iso image burned to usb and installed to nvme. I use modified acpi table to be able os to see NVME. (you have delete this branch :) - pcie-switch-testing )

**Comment by mariobalanica** [comment]
Can you expand a bit on the PCIe matter? Does NVME not work without patching ACPI, or are you using a PCIe switch in between?

That branch was just a hack that happens to work on Linux but will not do so on any other OS.

**Comment by harryzz** [comment]
> Can you expand a bit on the PCIe matter? Does NVME not work without patching ACPI, or are you using a PCIe switch in between?
> 
> That branch was just a hack that happens to work on Linux but will not do so on any other OS.

for sure not working ( may be for some patched kernels - armbian .. etc - can work i don't know ) Without acpi patch installer can't see the nvme.

**Comment by mariobalanica** [comment]
Weird, it does work fine for me & others without any ACPI or kernel patches. What NVME drive are you using?

dmesg output before and after patching ACPI would be helpful, if you're interested in debugging this further.

**Comment by harryzz** [comment]
> Weird, it does work fine for me & others without any ACPI or kernel patches. What NVME drive are you using?
> 
> dmesg output before and after patching ACPI would be helpful, if you're interested in debugging this further.

Hi
rock 5b: Samsung SSD 970 EVO Plus 2TB PCIe M.2 2280 SSD
orange pi 5 plus: Crucial P3 Plus 2TB PCIe M.2 2280 SSD

[edk2_rk3588_acpi.patch](https://github.com/edk2-porting/edk2-rk3588/files/12643485/edk2_rk3588_acpi.patch)
[dmesg.no_acpi_patch.txt](https://github.com/edk2-porting/edk2-rk3588/files/12643487/dmesg.no_acpi_patch.txt)
[dmesg.acpi_patched.txt](https://github.com/edk2-porting/edk2-rk3588/files/12643488/dmesg.acpi_patched.txt)

**Comment by athre0z** [comment]
As another data point: with 0.8 on my Rock 5B I see NVMe just fine without any ACPI patches with a NixOS 6.1-rc1 kernel. I have pretty much the same SSD as OP, except that it's the 1TB variant.

**Comment by harryzz** [comment]
the only difference if 6.6-rc1 is kernel version is this. But in pure ACPI this make no sense.

**Comment by mariobalanica** [comment]
Workaround available in 842db13abdcf46a2cc45570806dd7c0e0bc00db8

As for NVME, I was not able to reproduce the issue on CentOS Stream 9.
In your case it does not see the PCIe device at all, so it seems related to #66, although this is a single device.
