### ISSUE TITLE
Latest release broke opi5+

### ISSUE THREAD

**Issue by derzahla** [edk2-porting/edk2-rk3588#90]
Hi, I just installed the latest 0.8 release after noticing it was out. I had previous been running one of the nightlies from 3-4 weeks ago with great success on my opi5pluses.  

Now I get a boot failure with messages like(left out some redudant msgs, may be  some typeos):
```
Failed to set MokListRT: Invalid Parameter
...
import_mok_state() failed : invalid parameter
Continuing boot since secure mode is disabled

Synchronous Exception at 0x000000000E99AE89C
```

Boot does not continue and I am unable to find any new secure boot related settings I can adjust as a workaround. Please advise

Thanks

EDIT: Wanted to note I am booting from nvme and that I upgraded from and reverted back to working img: orangepi-5plus_UEFI_Release_d8039ee.img

**Comment by mariobalanica** [comment]
Hi, this is likely the same issue as #87.

Latest nightly build should work fine.
