### ISSUE TITLE
Rockchip Legacy 5.10 Kernel Freezes on Boot

### ISSUE THREAD

**Issue by milas** [edk2-porting/edk2-rk3588#98]
Thanks again for all the help in #93.

I'm now successfully hitting GRUB and starting the kernel, but it quickly freezes.

Over HDMI, I see the Radxa logo & progress bar, then GRUB, and then the boot starts:
```
EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
```

Nothing more appears there.

Over serial output:
<details>
<summary>bootloader</summary>
<pre>
U-Boot SPL board init
U-Boot SPL 2017.09-g5f53abfa1e-221223 #zzz (Dec 26 2022 - 09:10:09)
Trying to boot from MMC2
MMC: no card present
mmc_init: -123, time 0
spl: mmc init failed with error: -123
Trying to boot from MMC1
No misc partition
Trying fit image at 0x800 sector
## Checking nvdata 0x007c0000 ... OK
Jumping to U-Boot(0x00200000) via ARM Trusted Firmware(0x00040000)
Total: 591.281 ms

INFO:    Preloader serial: 2

                             GNU GRUB  version 2.06

  Booting `A - Talos v1.5.2-2-g89d7e7ba4-dirty'

EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
</pre>
</details>

<details>
<summary>kernel</summary>
<pre>
[   35.282631] Booting Linux on physical CPU 0x0000000000 [0x412fd050]
[   35.282661] Linux version 5.10.110-milas-g5426ee10da67-dirty (root@buildkitsandbox) (aarch64-none-linux-gnu-gcc (GNU Toolchain for the A-profile Architecture 10.3-2021.07 (arm-10.29)) 10.3.1 20210621, GNU ld3
[   35.282907] earlycon: uart8250 at MMIO32 0x00000000feb50000 (options '')
[   35.286870] printk: bootconsole [uart8250] enabled
[   35.287625] efi: EFI v2.70 by EDK II
[   35.287967] efi: SMBIOS=0xefd90000 SMBIOS 3.0=0xea670000 MEMATTR=0xee7c4298 ACPI 2.0=0xea690018 MEMRESERVE=0xea452e98 
[   35.289016] efi: memattr: Unexpected EFI Memory Attributes table version 2
[   35.655013] ACPI: Early table checksum verification disabled
[   35.655567] ACPI: RSDP 0x00000000EA690018 000024 (v02 RKCP  )
[   35.656131] ACPI: XSDT 0x00000000EA69FE98 000074 (v01 RKCP   RK3588   00000000      01000013)
[   35.656959] ACPI: FACP 0x00000000EA69FB98 000114 (v06 RKCP   RK3588   00000000 EDK2 00000000)
[   35.657789] ACPI: DSDT 0x00000000EA697518 000842 (v02 RKCP   RK3588   00000002 INTL 20200925)
[   35.658611] ACPI: DBG2 0x00000000EA69FA98 00005C (v00 RKCP   RK3588   00000000 EDK2 00000000)
[   35.659434] ACPI: GTDT 0x00000000EA69FD18 000060 (v02 RKCP   RK3588   00000000 EDK2 00000000)
[   35.660255] ACPI: APIC 0x00000000EA69E998 0002D4 (v04 RKCP   RK3588   00000000 EDK2 00000000)
[   35.661076] ACPI: MCFG 0x00000000EA69F818 00007C (v01 RKCP   RK3588   00000000 EDK2 00000000)
[   35.661897] ACPI: PPTT 0x00000000EA69ED98 000220 (v01 RKCP   RK3588   00000000 EDK2 00000000)
[   35.662716] ACPI: SPCR 0x00000000EA69FE18 000050 (v02 RKCP   RK3588   00000000 EDK2 00000000)
[   35.663537] ACPI: SSDT 0x00000000EA69E318 00026B (v05 RKCP   PCIE21L0 00000002 INTL 20200925)
[   35.664357] ACPI: SSDT 0x00000000EA69F018 00026B (v05 RKCP   PCIE21L2 00000002 INTL 20200925)
[   35.665178] ACPI: SSDT 0x00000000EA69C798 000269 (v05 RKCP   PCIE34L0 00000002 INTL 20200925)
[   35.666114] Zone ranges:
[   35.666360]   DMA      [mem 0x0000000000000000-0x00000000ffffffff]
[   35.666950]   DMA32    empty
[   35.667229]   Normal   [mem 0x0000000100000000-0x00000003ffffffff]
[   35.667818] Movable zone start for each node
[   35.668222] Early memory node ranges
[   35.668564]   node   0: [mem 0x0000000000000000-0x00000000001fffff]
[   35.669158]   node   0: [mem 0x0000000000200000-0x00000000007bffff]
[   35.669751]   node   0: [mem 0x00000000007c0000-0x00000000007effff]
[   35.670344]   node   0: [mem 0x00000000007f0000-0x00000000083fffff]
[   35.670938]   node   0: [mem 0x0000000008400000-0x00000000093fffff]
[   35.671531]   node   0: [mem 0x0000000009400000-0x00000000e9c5ffff]
[   35.672126]   node   0: [mem 0x00000000e9c60000-0x00000000ea44ffff]
[   35.672718]   node   0: [mem 0x00000000ea450000-0x00000000ea452fff]
[   35.673311]   node   0: [mem 0x00000000ea453000-0x00000000ea4b6fff]
[   35.673904]   node   0: [mem 0x00000000ea4b7000-0x00000000ea59ffff]
[   35.674496]   node   0: [mem 0x00000000ea5a0000-0x00000000ea68ffff]
[   35.675088]   node   0: [mem 0x00000000ea690000-0x00000000ea69ffff]
[   35.675681]   node   0: [mem 0x00000000ea6a0000-0x00000000ea7effff]
[   35.676273]   node   0: [mem 0x00000000ea7f0000-0x00000000efbfffff]
[   35.676866]   node   0: [mem 0x00000000efc00000-0x00000000effdffff]
[   35.677458]   node   0: [mem 0x00000000effe0000-0x00000000efffffff]
[   35.678051]   node   0: [mem 0x0000000100000000-0x00000003fbffffff]
[   35.678649]   node   0: [mem 0x00000003fc000000-0x00000003fc4fffff]
[   35.679241]   node   0: [mem 0x00000003fc500000-0x00000003ffefffff]
[   35.679834]   node   0: [mem 0x00000003fff00000-0x00000003ffffffff]
[   35.680428] Initmem setup node 0 [mem 0x0000000000000000-0x00000003ffffffff]
[   35.815386] cma: Reserved 16 MiB at 0x00000000eec00000
[   35.815913] psci: probing for conduit method from ACPI.
[   35.816415] psci: PSCIv1.1 detected in firmware.
[   35.816854] psci: Using standard PSCI v0.2 function IDs
[   35.817351] psci: Trusted OS migration not required
[   35.817818] psci: SMC Calling Convention v1.2
[   35.818646] percpu: Embedded 33 pages/cpu s94376 r8192 d32600 u135168
[   35.819410] Detected VIPT I-cache on CPU0
[   35.819848] CPU features: detected: GIC system register CPU interface
[   35.820459] CPU features: detected: Virtualization Host Extensions
[   35.821051] CPU features: detected: ARM errata 1165522, 1319367, or 1530923
[   35.821718] alternatives: patching kernel code
[   35.822701] Built 1 zonelists, mobility grouping on.  Total pages: 4064256
[   35.823361] Kernel command line: BOOT_IMAGE=/A/vmlinuz talos.platform=metal console=ttyFIQ0 console=tty1 talos.board=rock_5b earlycon=uart8250,mmio32,0xfeb50000 sysctl.kernel.kexec_load_disabled=1 talos.dash2
[   35.831287] Dentry cache hash table entries: 2097152 (order: 12, 16777216 bytes, linear)
[   35.833109] Inode-cache hash table entries: 1048576 (order: 11, 8388608 bytes, linear)
[   35.833860] mem auto-init: stack:off, heap alloc:on, heap free:off
[   35.843161] software IO TLB: mapped [mem 0x00000000eac00000-0x00000000eec00000] (64MB)
[   36.031483] Memory: 15847224K/16515072K available (18112K kernel code, 3702K rwdata, 6644K rodata, 7424K init, 619K bss, 651464K reserved, 16384K cma-reserved)
[   36.033028] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=8, Nodes=1
[   36.033689] ftrace: allocating 69442 entries in 272 pages
[   36.201240] ftrace: allocated 272 pages with 2 groups
[   36.202150] rcu: Hierarchical RCU implementation.
[   36.202603] rcu:     RCU event tracing is enabled.
[   36.203034]  Rude variant of Tasks RCU enabled.
[   36.203464]  Tracing variant of Tasks RCU enabled.
[   36.203919] rcu: RCU calculated value of scheduler-enlistment delay is 30 jiffies.
[   36.213182] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[   36.213889] GICv3: GIC: Using split EOI/Deactivate mode
[   36.214389] GICv3: 480 SPIs implemented
[   36.214754] GICv3: 0 Extended SPIs implemented
[   36.215196] GICv3: Distributor has no Range Selector support
[   36.215739] GICv3: 16 PPIs implemented
[   36.216141] GICv3: CPU0: found redistributor 0 region 0:0x00000000fe680000
[   36.216922] ITS: No ITS available, not enabling LPIs
[   36.217599] random: get_random_bytes called from start_kernel+0x3e0/0x5e0 with crng_init=0
[   36.217691] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[   36.219048] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[   36.220068] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[   36.220985] Console: colour dummy device 80x25
[   36.221449] printk: console [tty1] enabled
[   36.221850] printk: bootconsole [uart8250] disabled
I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot
I/TC: Secondary CPU 2 initializing
I/TC: Secondary CPU 2 switching to normal world boot
I/TC: Secondary CPU 3 initializing
I/TC: Secondary CPU 3 switching to normal world boot
I/TC: Secondary CPU 4 initializing
I/TC: Secondary CPU 4 switching to normal world boot
I/TC: Secondary CPU 5 initializing
I/TC: Secondary CPU 5 switching to normal world boot
I/TC: Secondary CPU 6 initializing
I/TC: Secondary CPU 6 switching to normal world boot
I/TC: Secondary CPU 7 initializing
I/TC: Secondary CPU 7 switching to normal world boot
</pre>
</details>

My device is a Radxa Rock 5B, and I'm using the Radxa kernel sources which are based off Rockchip legacy 5.10 rkr3.4.

Nothing really seems to be going obviously wrong, but it just halts at this point and the activity LED remains solid, so nothing seems to be happening.

Is this something you've seen before?

**Comment by mariobalanica** [comment]
You're booting in ACPI mode rather than DT.

**Comment by avi951** [comment]
Hello, @mariobalanica
Can you explain how to solve if the kernel freezes in between?


```
[    2.278904][    T1] mpp_vdpu1 fdb51000.avsd-plus: Adding to iommu group 1
[    2.279138][    T1] mpp_vdpu1 fdb51000.avsd-plus: probe device
[    2.279249][    T1] mpp_vdpu1 fdb51000.avsd-plus: reset_group->rw_sem_on=0
[    2.279257][    T1] mpp_vdpu1 fdb51000.avsd-plus: reset_group->rw_sem_on=0
[    2.279389][    T1] mpp_vdpu1 fdb51000.avsd-plus: probing finish
[    2.279728][    T1] mpp_vdpu2 fdb50400.vdpu: Adding to iommu group 1
[    2.279766][    T1] mpp_vdpu2 fdb50400.vdpu: probe device
[    2.279851][    T1] mpp_vdpu2 fdb50400.vdpu: reset_group->rw_sem_on=0
[    2.279856][    T1] mpp_vdpu2 fdb50400.vdpu: reset_group->rw_sem_on=0
[    2.279957][    T1] mpp_vdpu2 fdb50400.vdpu: probing finish
[    2.280119][    T1] mpp_vepu2 jpege-ccu: probing start
[    2.280124][    T1] mpp_vepu2 jpege-ccu: probing finish
[    2.280220][    T1] mpp_vepu2 fdb50000.vepu: Adding to iommu group 1
[    2.280256][    T1] mpp_vepu2 fdb50000.vepu: probing start
[    2.280334][    T1] mpp_vepu2 fdb50000.vepu: reset_group->rw_sem_on=0
[    2.280339][    T1] mpp_vepu2 fdb50000.vepu: reset_group->rw_sem_on=0
[    2.280463][    T1] mpp_vepu2 fdb50000.vepu: probing finish
[    2.280542][    T1] mpp_vepu2 fdba0000.jpege-core: Adding to iommu group 5
[    2.280628][    T1] mpp_vepu2 fdba0000.jpege-core: probing start
[    2.280727][    T1] mpp_vepu2 fdba0000.jpege-core: attach ccu success
[    2.280832][    T1] mpp_vepu2 fdba0000.jpege-core: probing finish
[    2.280896][    T1] mpp_vepu2 fdba4000.jpege-core: Adding to iommu group 6
[    2.280974][    T1] mpp_vepu2 fdba4000.jpege-core: probing start
[    2.281066][    T1] mpp_vepu2 fdba4000.jpege-core: attach ccu success
[    2.281168][    T1] mpp_vepu2 fdba4000.jpege-core: probing finish
[    2.281232][    T1] mpp_vepu2 fdba8000.jpege-core: Adding to iommu group 7
[    2.281308][    T1] mpp_vepu2 fdba8000.jpege-core: probing start
[    2.281400][    T1] mpp_vepu2 fdba8000.jpege-core: attach ccu success
[    2.281504][    T1] mpp_vepu2 fdba8000.jpege-core: probing finish
[    2.281568][    T1] mpp_vepu2 fdbac000.jpege-core: Adding to iommu group 8
[    2.281648][    T1] mpp_vepu2 fdbac000.jpege-core: probing start
[    2.281738][    T1] mpp_vepu2 fdbac000.jpege-core: attach ccu success
[    2.281839][    T1] mpp_vepu2 fdbac000.jpege-core: probing finish
[    2.282076][    T1] mpp-iep2 fdbb0000.iep: Adding to iommu group 9
[    2.282160][    T1] mpp-iep2 fdbb0000.iep: probe device
[    2.282275][    T1] mpp-iep2 fdbb0000.iep: allocate roi buffer failed
[    2.282375][    T1] mpp-iep2 fdbb0000.iep: probing finish
[    2.282550][    T1] mpp_jpgdec fdb90000.jpegd: Adding to iommu group 4
[    2.282714][    T1] mpp_jpgdec fdb90000.jpegd: probe device
[    2.282922][    T1] mpp_jpgdec fdb90000.jpegd: probing finish
[    2.283300][    T1] mpp_rkvdec2 fdc30000.rkvdec-ccu: rkvdec-ccu, probing start
[    2.283357][    T1] mpp_rkvdec2 fdc30000.rkvdec-ccu: ccu-mode: 1
[    2.283361][    T1] mpp_rkvdec2 fdc30000.rkvdec-ccu: probing finish
[    2.283461][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: Adding to iommu group 12
[    2.283748][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: rkvdec-core, probing start
[    2.283860][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: shared_niu_a is not found!
[    2.283864][    T1] rkvdec2_init:1022: No niu aclk reset resource define
[    2.283870][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: shared_niu_h is not found!
[    2.283874][    T1] rkvdec2_init:1025: No niu hclk reset resource define
[    2.283893][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: no regulator, devfreq is disabled
[    2.283948][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: core_mask=00010001
[    2.283953][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: attach ccu as core 0
[    2.284190][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: sram_start 0x00000000ff001000
[    2.284194][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: rcb_iova 0x00000000fff00000
[    2.284199][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: sram_size 491520
[    2.284203][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: rcb_size 1048576
[    2.284209][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: min_width 512
[    2.284216][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: rcb_info_count 20
[    2.284220][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [136, 24576]
[    2.284225][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [137, 49152]
[    2.284229][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [141, 90112]
[    2.284233][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [140, 49152]
[    2.284237][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [139, 180224]
[    2.284241][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [133, 49152]
[    2.284245][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [134, 8192]
[    2.284249][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [135, 4352]
[    2.284253][    T1] mpp_rkvdec2 fdc38100.rkvdec-core: [138, 13056]
```
